<template>
  <div class="ops-page">
    <header class="page-head"><div><p>{{ eyebrow }}</p><h1>{{ title }}</h1></div><button v-if="primaryLabel" class="primary" @click="dialogVisible=true"><Plus />{{ primaryLabel }}</button></header>
    <section class="metrics"><article v-for="item in metrics" :key="item.label"><small>{{ item.label }}</small><strong>{{ item.value }}</strong><em>{{ item.note }}</em></article></section>
    <section class="card">
      <div class="toolbar"><label><Search /><input v-model="keyword" :placeholder="searchPlaceholder" /></label><select v-model="status"><option value="">全部状态</option><option v-for="item in statuses" :key="item">{{ item }}</option></select><input v-model="date" type="date"><button class="query">查询</button><button @click="reset">重置</button><span>共 {{ filteredRows.length }} 条记录</span></div>
      <div class="table-wrap"><table><thead><tr><th v-for="col in columns" :key="col.key">{{ col.label }}</th><th>操作</th></tr></thead><tbody><tr v-for="(row,index) in filteredRows" :key="String(row.id ?? index)"><td v-for="col in columns" :key="col.key"><b v-if="col.emphasis">{{ format(row[col.key],col) }}</b><span v-else-if="col.key==='status'" class="tag" :class="tone(String(row[col.key]))">{{ row[col.key] }}</span><span v-else>{{ format(row[col.key],col) }}</span></td><td class="actions"><button @click="openDetail(row)">详情</button><button>编辑</button><button class="danger">{{ row.status==='停用'?'启用':'处理' }}</button></td></tr></tbody></table></div>
      <div v-if="filteredRows.length===0" class="empty">暂无匹配数据</div><footer><span>第 1 页，每页 10 条</span><div><button disabled>‹</button><button class="active">1</button><button disabled>›</button></div></footer>
    </section>
    <el-dialog v-model="dialogVisible" :title="primaryLabel" width="560px"><el-form label-position="top"><div class="form-grid"><el-form-item v-for="field in formFields" :key="field" :label="field" required><el-input v-model="draft[field]" :placeholder="`请输入${field}`" /></el-form-item></div><el-form-item label="备注"><el-input type="textarea" :rows="3" /></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="dialogVisible=false">保存</el-button></template></el-dialog>
    <el-drawer v-model="detailVisible" :title="`${title}详情`" size="430px"><div v-if="selected" class="detail"><h2>{{ selected[columns[0]?.key] }}</h2><dl><div v-for="col in columns" :key="col.key"><dt>{{ col.label }}</dt><dd>{{ format(selected[col.key],col) }}</dd></div></dl></div></el-drawer>
  </div>
</template>
<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { Plus, Search } from '@element-plus/icons-vue'
type Row=Record<string, any>; type Column={key:string;label:string;emphasis?:boolean;currency?:boolean}
const props=withDefaults(defineProps<{title:string;eyebrow:string;primaryLabel?:string;metrics:{label:string;value:string;note:string}[];columns:Column[];rows:Row[];statuses?:string[];formFields?:string[];searchPlaceholder?:string}>(),{primaryLabel:'',statuses:()=>[],formFields:()=>[],searchPlaceholder:'搜索关键字'})
const keyword=ref(''),status=ref(''),date=ref(''),dialogVisible=ref(false),detailVisible=ref(false),selected=ref<Row|null>(null),draft=reactive<Record<string,string>>({})
const filteredRows=computed(()=>props.rows.filter(row=>(!keyword.value||Object.values(row).some(v=>String(v).toLowerCase().includes(keyword.value.toLowerCase())))&&(!status.value||row.status===status.value)&&(!date.value||Object.values(row).includes(date.value))))
const format=(value:any,col:Column)=>col.currency?`¥ ${Number(value||0).toLocaleString('zh-CN',{minimumFractionDigits:2})}`:(value??'—')
const tone=(value:string)=>value.includes('完成')||value.includes('正常')||value.includes('在售')||value.includes('已支付')?'green':value.includes('待')||value.includes('预警')?'orange':value.includes('停')||value.includes('取消')||value.includes('驳回')?'red':'blue'
function reset(){keyword.value='';status.value='';date.value=''} function openDetail(row:Row){selected.value=row;detailVisible.value=true}
</script>
<style scoped>
.ops-page{color:#29384f}.page-head{margin:3px 2px 14px;display:flex;align-items:flex-end;justify-content:space-between}.page-head p{margin:0;color:#98a4b6;font-size:12px}.page-head h1{margin:3px 0 0;font-size:24px}.primary{height:36px;padding:0 14px;display:flex;align-items:center;gap:7px;color:#fff;border:0;border-radius:7px;background:#1677ff}.primary svg,.toolbar svg{width:15px}.metrics{margin-bottom:12px;display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metrics article,.card{border:1px solid #e6ebf2;border-radius:8px;background:#fff}.metrics article{padding:15px;display:grid}.metrics small{color:#8290a3;font-size:10px}.metrics strong{font-size:21px}.metrics em{color:#169c73;font-size:9px;font-style:normal}.card{padding:15px}.toolbar{margin-bottom:14px;display:flex;align-items:center;gap:9px}.toolbar label{width:260px;height:34px;padding:0 10px;display:flex;align-items:center;gap:7px;border:1px solid #dde4ed;border-radius:6px}.toolbar label input{width:100%;border:0}.toolbar>input,.toolbar select,.toolbar button{height:34px;padding:0 10px;border:1px solid #dde4ed;border-radius:6px;background:#fff}.toolbar .query{color:#fff;border-color:#1677ff;background:#1677ff}.toolbar>span{margin-left:auto;color:#9ba6b5;font-size:10px}.table-wrap{overflow-x:auto;border:1px solid #e8edf3;border-radius:7px}table{width:100%;min-width:900px;border-collapse:collapse}th,td{padding:12px;text-align:left;border-bottom:1px solid #edf1f5;font-size:11px}th{color:#718096;background:#f7f9fc}.tag{padding:4px 7px;border-radius:4px}.tag.green{color:#169c73;background:#e8f8f2}.tag.orange{color:#d57b13;background:#fff3df}.tag.red{color:#df555a;background:#fff0f0}.tag.blue{color:#1677ff;background:#eaf3ff}.actions{white-space:nowrap}.actions button{margin-right:8px;color:#1677ff;border:0;background:transparent}.actions .danger{color:#e55358}.empty{padding:30px;text-align:center;color:#9aa5b4}.card footer{padding-top:13px;display:flex;justify-content:space-between;color:#99a5b5;font-size:10px}.card footer div{display:flex;gap:5px}.card footer button{width:28px;height:28px;border:1px solid #e0e6ee;border-radius:5px;background:#fff}.card footer .active{color:#fff;background:#1677ff}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.detail h2{margin-top:0}.detail dl{display:grid;gap:10px}.detail dl div{display:grid;grid-template-columns:100px 1fr;padding-bottom:9px;border-bottom:1px solid #edf1f5}.detail dt{color:#98a4b6}.detail dd{margin:0}@media(max-width:1000px){.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:680px){.metrics{grid-template-columns:1fr}.toolbar{flex-wrap:wrap}.toolbar label{width:100%}.toolbar>span{width:100%;margin:0}.form-grid{grid-template-columns:1fr}}
</style>
